name: PR Auto Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    # Prevent secrets exposure on forks
    if: ${{ !github.event.pull_request.draft && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate PR diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          git diff --unified=0 origin/${{ github.event.pull_request.base.ref }}...HEAD > pr.diff || true
          test -s pr.diff || echo "No changes detected." > pr.diff

      - name: AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          LLM_MODEL: ${{ vars.LLM_MODEL || 'gpt-4o-mini' }}
        run: node scripts/pr_auto_review.mjs

